server:
  port: 8080


spring:
  application:
    name: spring-boot-enterprise-boilerplate
  datasource:
    url: jdbc:postgresql://localhost:5432/boilerplate_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    open-in-view: false
  mail:
    host: localhost
    port: 1025 # Mailhog
    username: null
    password: null
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  data:
    redis:
      host: localhost
      port: 6379

# Security Configuration
security:
  jwt:
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970 # Replace with a strong secret in prod
    expiration-time: 3600000 # 1 hour
    refresh-token-expiration-time: 86400000 # 1 day

# Logging
logging:
  level:
    root: INFO
    com.boilerplate: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Swagger / OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
